# Generated by Django 5.0.6 on 2024-05-16 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_category_jobs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='jobs',
        ),
    ]
