# Generated by Django 5.0.6 on 2024-05-16 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_remove_category_jobs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subtitle', models.TextField(max_length=500)),
                ('email', models.TextField(max_length=500)),
                ('web', models.TextField(max_length=500)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='Company_logo')),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_type',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='email',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='required',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='web',
        ),
        migrations.AddField(
            model_name='category',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='Category_logo'),
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default='exit', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobs',
            name='jobs_type',
            field=models.CharField(choices=[('FullTime', 'Full Time'), ('PartTime', 'Part Time'), ('Remote', 'Remote'), ('Freelance', 'Freelance')], default='exit', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobs',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='Jobs_logo'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='experience',
            field=models.IntegerField(choices=[(1, '1-2 Years'), (2, '2-3 Years'), (3, '3-6 Years'), (4, '6-more..')]),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='location',
            field=models.TextField(max_length=100),
        ),
        migrations.AddField(
            model_name='jobs',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs_company', to='jobs.company'),
        ),
    ]
