# Generated by Django 5.0.6 on 2024-05-17 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_company_remove_category_name_type_remove_jobs_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
