# Generated by Django 5.0.6 on 2024-05-18 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_jobs_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='jobs_type',
            field=models.CharField(choices=[('FullTime', 0), ('PartTime', 1), ('Remote', 2), ('Freelance', 3)], max_length=30),
        ),
    ]
