# Generated by Django 5.0.6 on 2024-05-18 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_alter_jobs_jobs_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='jobs_type',
            field=models.IntegerField(choices=[('FullTime', 0), ('PartTime', 1), ('Remote', 2), ('Freelance', 3)]),
        ),
    ]
