# Generated by Django 5.0.6 on 2024-05-18 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_alter_jobs_jobs_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='experience',
            field=models.IntegerField(choices=[('1-2 Years', 0), ('2-3 Years', 1), ('3-6 Years', 2), ('6-more..', 3)]),
        ),
    ]
