# Generated by Django 5.0.6 on 2024-05-18 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_alter_jobs_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='experience',
            field=models.IntegerField(choices=[(1, '1-2 Years'), (2, '2-3 Years'), (3, '3-6 Years'), (4, '6-more..')]),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='jobs_type',
            field=models.CharField(choices=[('FullTime', 'Full Time'), ('PartTime', 'Part Time'), ('Remote', 'Remote'), ('Freelance', 'Freelance')], max_length=30),
        ),
    ]
